### ISSUE TITLE
environments and kernels

### ISSUE THREAD

**Issue by biophyser** [Zsailer/python-setup-for-scientists#8]
Start with a short explanation why you would want an environment. Then how to make one using conda and finally how to set up a kernel for jupyter for that environment.

**Comment by lcwheeler** [comment]
Looks good, Anderson! Should we also include a description of how to create virtual environments using venv? By the way, I like the Beyond Thunderdome reference.

**Comment by lcwheeler** [comment]
Oh also, the new page needs to be added to the index.rst in order for it to get displayed on the

**Comment by lcwheeler** [comment]
....rendered page.

**Comment by biophyser** [comment]
We could. I guess that depends if Zach goes all-in on conda for python installation. If he does that then maybe have a link to other ways you can create virtual environments. This seems the simplest route.

**Comment by biophyser** [comment]
Yep, I forgot the `index.rst` last night. I'll get on that.

**Comment by biophyser** [comment]
@Zsailer said he's planning on only talking about miniconda to install python so I think I'll just stick with making virtual environments with conda.

**Comment by lcwheeler** [comment]
Okay, sounds like a plan.

**Comment by biophyser** [comment]
I'm closing this. The backbone is there we'll just need to revise it *ad infinitum*.
